### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by kobevino** [kobevino/kobevino-blog#2]
### TODO List

- [x] config nextjs
- [x] config biome and lefthook
- [x] github actions ci/cd
- [x] config commitlint
- [x] blog design work with mantine ui
- [x] mdx, code highlight
- [x] 3d main design using three.js (text particle animation)
- [x] add utterances on post
- [x] about page (english resume, korean resume, portpolio) pdf 
- [x] swing animation (@kobevino)
- [x] Post item hover effect
- [x] Logo animation

**Comment by kobevino** [comment]
3d main design reference

https://rpj.bembi.dev/#night-sky
https://devicon.dev/

**Comment by kobevino** [comment]
utterances reference

https://sukvvon.tistory.com/72

**Comment by kobevino** [comment]
ts particles  tutorial

https://particles.js.org/video.html

**Comment by kobevino** [comment]
swing animation reference

https://codepen.io/ChrisMla/pen/jWMLWY

**Comment by kobevino** [comment]
logo typing animation reference 

https://codepen.io/geoffgraham/pen/jrWwWM

**Comment by kobevino** [comment]
css hover effect (pure css 3D perpective)

https://www.proglobalbusinesssolutions.com/css-hover-effects/
